sudo: required

env:
  global:
    - TAG=master DOCKER_TAG=automatic

services:
  - docker

script:
  - echo "Building octroprint branch/tag $TAG into bodrick/octoprint:$DOCKER_TAG"
  - docker build --build-arg tag=$TAG -t bodrick/octoprint:$DOCKER_TAG .
  - if [[ "$DOCKER_TAG" != "automatic" ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - if [[ "$DOCKER_TAG" != "automatic" ]]; then docker push bodrick/octoprint:$DOCKER_TAG; fi
