version: '2'
services:
  octoprint:
    build: .
    image: bodrick/octoprint
    container_name: octoprint
    ports:
      - 5000:5000
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
       - octoprint_data:/home/octoprint/.octoprint
       - octoprint-packages:/opt/octoprint/venv/lib/python2.7/site-packages
